# Generated by Django 5.2.12 on 2026-04-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RenameIndex(
            model_name='otprequest',
            new_name='accounts_ot_email_200645_idx',
            old_name='accounts_ot_email_5404b9_idx',
        ),
    ]
